version: 2
jobs:
  build:
    macos:
      xcode: '13.4.1'
    steps:
      - run:
          name: Swap node versions
          command: |
            set +e
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install v18.20.4
            nvm alias default v18.20.4

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - checkout
      - run: yarn
      - run: mkdir -p ~/reports
      - run: yarn test:ci
      - run: yarn run dist
      - run: mv dist/*-x64.dmg dist/Kap-x64.dmg
      - run: mv dist/*-arm64.dmg dist/Kap-arm64.dmg
      - store_artifacts:
          path: dist/Kap-x64.dmg
      - store_artifacts:
          path: dist/Kap-arm64.dmg
      - store_test_results:
          path: ~/reports
  sentry-release:
    docker:
      - image: cimg/node:lts
    environment:
      SENTRY_ORG: wulkano-l0
      SENTRY_PROJECT: kap
    steps:
      - checkout
      - run: |
          curl -sL https://sentry.io/get-cli/ | bash
          export SENTRY_RELEASE=$(yarn run -s sentry-version)
          sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
          sentry-cli releases set-commits --auto $SENTRY_RELEASE
          sentry-cli releases finalize $SENTRY_RELEASE

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/ # Force CircleCI to build on tags
      - sentry-release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
